// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU3TtSt6Mvg2HxGnFskk7hS-kc8uH5F6I',
    appId: '1:505266238198:web:9268f43f747e66cc5572d7',
    messagingSenderId: '505266238198',
    projectId: 'seblak-6cf5a',
    authDomain: 'seblak-6cf5a.firebaseapp.com',
    storageBucket: 'seblak-6cf5a.appspot.com',
    measurementId: 'G-EBVV4061ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8quatQNcawnUEc_ifabmPX2a9BP65vbw',
    appId: '1:505266238198:android:3dada3b7804534005572d7',
    messagingSenderId: '505266238198',
    projectId: 'seblak-6cf5a',
    storageBucket: 'seblak-6cf5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy0VBpH1asJ2RkiblUcm2lxfLurRavHZc',
    appId: '1:505266238198:ios:2d9aeea1feddac155572d7',
    messagingSenderId: '505266238198',
    projectId: 'seblak-6cf5a',
    storageBucket: 'seblak-6cf5a.appspot.com',
    iosBundleId: 'com.example.seblak2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy0VBpH1asJ2RkiblUcm2lxfLurRavHZc',
    appId: '1:505266238198:ios:fbdb45b5be307f5e5572d7',
    messagingSenderId: '505266238198',
    projectId: 'seblak-6cf5a',
    storageBucket: 'seblak-6cf5a.appspot.com',
    iosBundleId: 'com.example.seblak2.RunnerTests',
  );
}
